version: '3.8'
services:
  python-backend:
    build: ./python-backend
    ports:
      - "8000:8000"
  nestjs-backend:
    build: ./nestjs-backend
    ports:
      - "3000:3000"
  angular-frontend:
    build: ./angular-frontend
    ports:
      - "4200:80"
